const CountryCodes: Record<string, string> = {
	AUD: "australia",
	BRL: "brazil",
	CAD: "canada",
	CLP: "chile",
	CNY: "china",
	CNH: "china",
	CZK: "czechrepublic",
	DKK: "denmark",
	HKD: "hongkong",
	HUF: "hungary",
	INR: "india",
	IDR: "indonesia",
	JPY: "japan",
	MYR: "malaysia",
	MXN: "mexico",
	NOK: "norway",
	PHP: "philippines",
	PLN: "poland",
	QAR: "qatar",
	RON: "romania",
	RUB: "russia",
	SAR: "saudiarabia",
	SGD: "singapore",
	ZAR: "southafrica",
	//KRW: "korea",
	CHF: "switzerland",
	TWD: "taiwan",
	THB: "thailand",
	TRY: "turkey",
	USD: "unitedstates",
	EUR: "europeanunion",
	GBP: "unitedkingdom",
	AED: "unitedarabemirates",
	KRW: "southkorea",
	VND: "vietnam",
	SEK: "sweden",
	NZD: "newzealand",
};

export default CountryCodes;
