name: Publish Web Staging

on:
  push:
    branches:
      - staging

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - projectName: "web-staging"

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Run build
        run: yarn web-build:staging

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_STAGING_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_STAGING_ACCOUNT_ID }}
          projectName: ${{ matrix.projectName }}
          directory: ./apps/wiredup-web/dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
